// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"personal_schedule_service/internal/eventbus/handler"
	"personal_schedule_service/internal/repos"
)

// Injectors from handler.wire.go:

func InjectSyncAuthHandler() *handler.SyncAuthHandler {
	userRepo := repos.NewUserRepo()
	syncAuthHandler := handler.NewSyncAuthHandler(userRepo)
	return syncAuthHandler
}
